#!/bin/bash
git config --global user.email "<email-addr>"
git config --global user.name "<firstname lastname"
git config pull.rebase true
git config --global init.defaultBranch main

# use this, even on Windows; use cygwin on Windows or WSL always
git config --global core.autocrlf false
git config --global core.eol lf

# --
cp $HOME/.gitconfig $HOME/.gitconfig-<tag>
